<?php
require_once 'includes/auth.php'; require_once 'config/db.php'; require_once 'includes/functions.php';
require_permission('reports.view'); $pageTitle='Dashboard Analytics';
$trend=$pdo->query("SELECT DATE(sale_date) day, SUM(grand_total) revenue, COUNT(*) sales FROM sales WHERE sale_date >= DATE_SUB(CURDATE(),INTERVAL 13 DAY) GROUP BY DATE(sale_date) ORDER BY day")->fetchAll(PDO::FETCH_ASSOC);
$top=$pdo->query("SELECT p.name, SUM(si.qty) qty, SUM(si.total) revenue FROM sale_items si JOIN products p ON p.id=si.product_id GROUP BY p.id,p.name ORDER BY qty DESC LIMIT 10")->fetchAll(PDO::FETCH_ASSOC);
$margins=$pdo->query("SELECT COALESCE(SUM(si.total),0) revenue, COALESCE(SUM(si.qty*COALESCE(p.cost,0)),0) cost FROM sale_items si JOIN products p ON p.id=si.product_id")->fetch(PDO::FETCH_ASSOC);
$cashiers=$pdo->query("SELECT u.full_name, COUNT(s.id) sales, COALESCE(SUM(s.grand_total),0) revenue FROM users u LEFT JOIN sales s ON s.user_id=u.id AND s.sale_date >= DATE_SUB(CURDATE(),INTERVAL 30 DAY) GROUP BY u.id,u.full_name ORDER BY revenue DESC LIMIT 10")->fetchAll(PDO::FETCH_ASSOC);
include 'includes/header.php'; ?>
<h2>Dashboard analytics</h2><p class="text-muted">Sales and staff performance for the latest available transactions.</p>
<div class="row g-3"><div class="col-md-4"><div class="card"><div class="card-body"><small>Sales revenue</small><div class="display-6">KSh <?= number_format($margins['revenue'],2) ?></div></div></div></div><div class="col-md-4"><div class="card"><div class="card-body"><small>Gross profit</small><div class="display-6">KSh <?= number_format($margins['revenue']-$margins['cost'],2) ?></div></div></div></div><div class="col-md-4"><div class="card"><div class="card-body"><small>Gross margin</small><div class="display-6"><?= $margins['revenue'] ? number_format((($margins['revenue']-$margins['cost'])/$margins['revenue'])*100,1) : '0.0' ?>%</div></div></div></div></div>
<div class="row g-3 mt-1"><div class="col-lg-6"><div class="card"><div class="card-header">Sales trend (14 days)</div><div class="card-body"><table class="table table-sm"><thead><tr><th>Date</th><th>Sales</th><th class="text-end">Revenue</th></tr></thead><tbody><?php foreach($trend as $r): ?><tr><td><?= htmlspecialchars($r['day']) ?></td><td><?= $r['sales'] ?></td><td class="text-end">KSh <?= number_format($r['revenue'],2) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div><div class="col-lg-6"><div class="card"><div class="card-header">Top products</div><div class="card-body"><table class="table table-sm"><thead><tr><th>Product</th><th>Units</th><th class="text-end">Revenue</th></tr></thead><tbody><?php foreach($top as $r): ?><tr><td><?= htmlspecialchars($r['name']) ?></td><td><?= $r['qty'] ?></td><td class="text-end">KSh <?= number_format($r['revenue'],2) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div></div>
<div class="card mt-3"><div class="card-header">Cashier performance (30 days)</div><div class="card-body"><table class="table table-sm"><thead><tr><th>Cashier</th><th>Sales</th><th>Revenue</th></tr></thead><tbody><?php foreach($cashiers as $r): ?><tr><td><?= htmlspecialchars($r['full_name']) ?></td><td><?= $r['sales'] ?></td><td>KSh <?= number_format($r['revenue'],2) ?></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php include 'includes/footer.php'; ?>
